triv: check pre commit

diff --git a/bin/git-hooks/pre-commit b/bin/git-hooks/pre-commit
--- a/bin/git-hooks/pre-commit
+++ b/bin/git-hooks/pre-commit
@@ -2,19 +2,32 @@
 #
 # source: https://yaroslavgrebnov.com/blog/bash-docker-check-container-existence-and-status/
 #
-files=$(git diff --cached --name-only --diff-filter=ACM -- '*.php');
+files=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
 if [ -z "$files" ]
 then
-	echo 'Empty changed files - skipping format\n'
+    echo 'Empty changed files - skipping format\n'
 else
-	# echo 'Changed files:\n'
-	# echo $files
-	echo '\n\n-- Formatting --'
+    echo '\n\n-- Formatting --'
 
-	if [ $( docker compose ps --status=running | grep php | wc -l ) -gt 0 ]
-	then
-		docker compose exec -T php ./vendor/bin/php-cs-fixer fix --config=".php-cs-fixer.php" $files
-	else
-		echo 'PHP container not running - skipping format\n'
-	fi
+    # Check if the PHP container is running using Sail
+    if [ $(./vendor/bin/sail ps --status=running | grep -c lacomp-laravel) -gt 0 ]
+    then
+        echo "PHP container is running. Running php-cs-fixer..."
+        ./vendor/bin/sail exec -T laravel.test ./vendor/bin/php-cs-fixer fix --config=".php-cs-fixer.php" $files
+
+        # Capture the result of php-cs-fixer
+        FIXER_EXIT_CODE=$?
+        if [ $FIXER_EXIT_CODE -ne 0 ]
+        then
+            echo "php-cs-fixer failed with exit code $FIXER_EXIT_CODE. Skipping commit.\n"
+            exit 1  # Block commit if php-cs-fixer fails
+        else
+            echo "php-cs-fixer completed successfully.\n"
+        fi
+    else
+        echo "PHP container is not running. Skipping format.\n"
+    fi
 fi
+
+# Allow the commit to continue (if no error occurred)
+exit 0
